### ISSUE TITLE
leer tabla rom -parcial-

### ISSUE THREAD

**Issue by manuelcgallucci** [fiuba-labo-de-micro-miercoles/2019-2c-Manuel_Cabeza#10]
Subí el ejercicio con su consigna, quería saber si estaba correcto.

**Comment by rarias** [comment]
https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-Manuel_Cabeza/blob/master/Proyectos_asm/leer_tabla_rom.asm
Comentado
