### ISSUE TITLE
Código sqrt

### ISSUE THREAD

**Issue by manuelcgallucci** [fiuba-labo-de-micro-miercoles/2019-2c-Manuel_Cabeza#11]
Buenas, queria saber si esta correcto el codigo "raiz_cuadrada" con doble presicion. Ademas tenia una duda respecto a cuando nos dicen que supongamos que disponemos de una rutina por ej. "Suponer que existe la rutina DIV (Ej. R5|R4 = DIV(R5|R4, R3|R2))". Se puede directamente escribir el llamado a la instruccion de la forma DIV R5|R4, R3|R2 ??

**Comment by pimartos** [comment]
Hola,
Si, esta bien, el tema es que cuando te dicen que existe la rutina DIV, significa que podes cargar en R5|R4 el dividendo, en R3|R2 el divisor y hacer CALL DIV; no que existe la instruccion DIV (en ningun enunciado suponemos la existencia de una instruccion que no este en el set de instrucciones)

cordialmente,
Pedro
