### ISSUE TITLE
Simulador JK -error en la lógica-

### ISSUE THREAD

**Issue by manuelcgallucci** [fiuba-labo-de-micro-miercoles/2019-2c-Manuel_Cabeza#2]
Tengo un error en la primera línea de esta parte del código, es porque no se puede usar LDI con un registro con operaciones lógicas?

JK:                            ; R16 es un registro auxiliar 
	LDI R16, (~(R18>>K))
	OR R16, R17
	OR ~(R17), R18>>J
	AND R17, R16
	
	OUT PINB, R17
	JMP CLK_BAJO

**Comment by pimartos** [comment]
Hola,
En "LDI R16, (\~(R18>>K))"
el segundo argumento de la instruccion tiene que ser una constante, y le estas poniendo un registro; por otra parte cosas como (~(R18>>K)) tienen que poder resolverse en tiempo de compilacion.

cordialmente,
Pedro
