### ISSUE TITLE
Simulador JK -Error en código general-

### ISSUE THREAD

**Issue by manuelcgallucci** [fiuba-labo-de-micro-miercoles/2019-2c-Manuel_Cabeza#3]
Este es el código que armé después de la clase del miercoles para simular un JK. El mismo no anda y se rompe en la línea OR R16, (1<<Q) al principio con un error de invalid register. Intentando distintas formas no logro entender que es lo que esta mal ya que es lo que tengo copiado en la carpeta. Además quería saber si existe una mejor forma de hacer la lógica del JK? Como por ejemplo algún comando que permita hacer el equivalente a R18 = not(R18>>2) ?

MAIN:
	.EQU Q = 3
	.EQU J = 2
	.EQU K = 1
	.EQU CLK = 0
	IN R16, DDRB 
	OR R16, (1<<Q) ; Inicializo los bits de R16 como entradas y salidas
	AND R16, ~((1<<J)|(1<<K)|(1<<CLK)) 
	OUT DDRB, R16
	LDI R17, 1   ; Aca es donde se guarda Q, que arranca en 1	

CLK_BAJO:
	IN R18, PINB
	SBIC PINB, CLK
	JMP CLK_BAJO
	RJMP CLK_ALTO
		
CLK_ALTO:
	IN R18, PINB 
	SBIS PINB, CLK
	JMP CLK_BAJO
	CALL JK
	JMP CLK_BAJO

JK: ; R19 es un registro auxiliar 
	MOV R16, R17
	COM R16              ; R16 continen ahora a -Qn
	MOV R19, R18
	ASR R19    
	ASR R19
	OR R16, R19     ; R16 con R19, solo importa el primer bit
	MOV R19, R18
	ASR R19    
	COM R19     ; El primer bit de R19 es ahora K neg
	OR  R17, R19
	AND R17, R16
	
	OUT PINB, R17
	JMP CLK_BAJO

**Comment by pimartos** [comment]
Hola,
El problema de OR R16, (1<<Q) es que las operaciones logicas se hacen entre registros, no entre registro y constante. 
Primero tenes que mover el valor de la constante a un registro y despues hacer la operacion logica entre los registros. Lo mismo se aplica a R18

cordialmente,
Pedro
