### ISSUE TITLE
Codigo promedio 

### ISSUE THREAD

**Issue by manuelcgallucci** [fiuba-labo-de-micro-miercoles/2019-2c-Manuel_Cabeza#4]
Subí el código para el promedio con números negativos, con el carry arreglado como vimos en clase. El código funciona en la simulación pero quería verificar si esta correcto.

**Comment by fbaglivo** [comment]
Hola Manuel, hay algo raro en la resolución. Por que si el numero es positivo trabajas con precision doble (R18R17) y si es negativo con [precisión simple](https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-primer-proyecto-ManuelCabeza/blob/32e347de99b8dedf7e5a37b002f645eaaade7e61/Proyectos_asm/promedio.asm#L44) R17? Que pasa en el caso extremo en el que sumas -127 las 8 veces?

**Comment by manuelcgallucci** [comment]
Ahí modifique el código para doble precisión pero se rompe cuando le pongo 81 (-127) en los 8 registros. Cuando hago esto la respuesta es 01 con solo la bandera H en 1. Cual es el problema ??

**Comment by rarias** [comment]
Ahí te marco un error
https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-Manuel_Cabeza/blob/master/Proyectos_asm/valor_medio.asm
