### ISSUE TITLE
Ejercicio conversion de C a F

### ISSUE THREAD

**Issue by manuelcgallucci** [fiuba-labo-de-micro-miercoles/2019-2c-Manuel_Cabeza#5]
Viendo el ejercicio de parcial: "Codificar una rutina que recibe la temp. en Celcius en R0 y en R1 la devuelve en Fareheit. Con C * (9/5) + 32 = F. Sugerencia 9/5 = 1.8 = 0001,11001101b con un error menor al 5%". Mi pregunta es, en que ayuda la sugerencia, es decir aplico un numero con coma a una función del tipo MULS,  y como lo defino ese numero con coma??

**Comment by rarias** [comment]
1,8 = n/d
d = denominador n=numerador
i.e. se busca una aproximación fraccionaria del 1,8 pero, de manera que la cuenta de multiplicar por el 1,8 sea "fácil".
Como la instrucción MUL existe  (MULS no para el 328) basta con elegir d = 2^algo para que dividir sólo sea un shifteo.
