### ISSUE TITLE
Ej. Filtro de parcial

### ISSUE THREAD

**Issue by manuelcgallucci** [fiuba-labo-de-micro-miercoles/2019-2c-Manuel_Cabeza#9]
Subo el ejercicio del parcial del filtro, con las consignas del ejercicio comentadas en la parte superior. Esta correcto?

**Comment by rarias** [comment]
https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-Manuel_Cabeza/blob/master/Proyectos_asm/filtro.asm
Corregido en el mismo texto
